### ISSUE TITLE
About epic、

### ISSUE THREAD

**Issue by wangxiujielalala** [debadityaroy/LatentGoal#3]
Sorry to bother you. I have noticed that the file organization format of the training.csv for the epic-kitchens-55 data set is different from that of the test set (test_seen.csv). I got  the two files from your link (https://github.com/fpv-iplab/rulstm/tree/master/RULSTM/data/ek55). The two files have different numbers of columns. What is the specific meaning of each column? In Table 3 I note that the test set results of seen Kitchens contain the predicted results of verbs, nouns, and actions. Should the organization of the two CSV files be the same? Looking forward to your reply.

**Comment by debadityaroy** [comment]
Hi
Yes the CSV format is different in training.csv and test_seen.csv
1. For training.csv, the columns are - segment_id, video_id, start_frame, end_frame, verb, noun, action

2. For test_seen.csv, the columns are - segment_id, video_id, start_frame, end_frame
